modLoader="javafml"
loaderVersion="[2,)"

license="MIT"

[[mods]]
modId="ancient_horizons"
version="0.0.1"
displayName="Ancient Horizons"
description='''Example mod'''

[[dependencies.ancient_horizons]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.ancient_horizons]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"